import google.generativeai as genai

genai.configure(api_key="AIzaSyAe64j4GtNYpJGQQK9GSLSQOzpImHfr10Y")

# Set up the model
generation_config = {
  "temperature": 1,
  "top_p": 1,
  "top_k": 1,
  "max_output_tokens": 2048,
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  }
]

model = genai.GenerativeModel(model_name="gemini-pro",
                              generation_config=generation_config,
                              safety_settings=safety_settings)
def gen_ai(prompt): 
    global msg
    msg = prompt

    prompt_parts = [
      " ",
      "input:you can assist both physical and virtual , you can pickup drop pick and place put ,only these actions using cmds",
      "output: Okay i will do as per the command",
      "input: Hiii"
      "output: Hello! How can I assist you today?"
      "input: Whats your name"
      "output: I can assist both physical and virtual task"      
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Move slightly up.",
      "output: _move(up) # Moving slightly up.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Move slightly left.",
      "output: _move(left) # Moving left.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Move left.",
      "output: _move(left) # Moving left.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Move right.",
      "output: _move(right) # Moving right.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl .",
      "output: _move(down) # Moving down.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the ball.",
      "output: _pickup(ball) # Picking up the ball.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the wood.",
      "output: _pickup(wood) #Picking up the wood.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the battery.",
      "output: _pickup(battery) # Picking up the battery.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the yellow object.",
      "output: _pickup(ball) # Picking up the yellow object.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the wood-colored object.",
      "output: _pickup(wood) # Picking up the wood-colored object.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the silver object.",
      "output: _pickup(battery) # Picking up the silver object.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Drop the object.",
      "output: _drop() # Dropping the object.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Drop the ball.",
      "output: _drop() # Dropping the ball.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Drop the wood.",
      "output: _drop() # Dropping the wood.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Drop the battery.",
      "output: _drop() # Dropping the battery.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Put the ball inside the bowl.",
      "output: _put(bowl) #Putting the ball inside the bowl.",
      "input: you can see   a silver battery , wooden object , white bowl . Put the ball inside the bowl.",
      "output: sorry i cant see any ball but i cant see battery,wood,bowl",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Put the wood inside the bowl.",
      "output: _put(bowl) # Putting the wood inside the bowl.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Put the battery inside the bowl.",
      "output: _put(bowl) # Putting the battery inside the bowl.",
      "input: you can see   a wooden object , white bowl . Put the battery inside the bowl.",
      "output: sorry i cant see any ball but i cant see wood,bowl",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the ball and place it in the bowl.",
      "output: _pickup(ball)place(bowl) # Picking up the ball and placing it in the bowl.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the wood and drop it in the bowl.",
      "output: _pickup(wood)place(bowl) # Picking up the wood and dropping it in the bowl.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the battery and put it in the bowl.",
      "output: _pickup(battery)place(bowl) # Picking up the battery and putting it in the bowl.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the yellow object and place it in the bowl.",
      "output: _pickup(ball)place(bowl) # Picking up the yellow object and placing it in the bowl.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the silver object and drop it in the bowl.",
      "output: _pickup(battery)place(bowl) # Picking up the silver object and dropping it in the bowl.",
      "input: you can see   a yellow ball , silver battery , wooden object , white bowl . Pick up the wood-colored object and put it in the bowl.",
      "output: _pickup(wood)place(bowl) # Picking up the wood-colored object and putting it in the bowl.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Move slightly up.",
      "output: _move(up) # Moving slightly up.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Move slightly left.",
      "output: _move(left) # Moving left.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Move left.",
      "output: _move(left) # Moving left.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Move right.",
      "output: _move(right) # Moving right.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Move down.",
      "output: _move(down) # Moving down.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the ball.",
      "output: _pickup(ball) # Picking up the ball.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the wood.",
      "output: _pickup(wood) # Picking up the wood.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the battery.",
      "output: _pickup(battery) # Picking up the battery.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the yellow object.",
      "output: _pickup(ball) # Picking up the yellow object.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the wood-colored object.",
      "output: _pickup(wood) # Picking up the wood-colored object.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the silver object.",
      "output: _pickup(battery) # Picking up the silver object.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Drop the object.",
      "output: _drop() # Dropping the object.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Drop the ball.",
      "output: _drop() # Dropping the ball.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Drop the wood.",
      "output: _drop() # Dropping the wood.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Drop the battery.",
      "output: _drop() # Dropping the battery.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Put the ball inside the bowl.",
      "output: _put(bowl) # Putting the ball inside the bowl.",
      "input: You can see a silver battery , wooden object , white bowl . Put the ball inside the bowl.",
      "output: Sorry, I can't see any ball but I can see battery, wood, bowl.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Put the wood inside the bowl.",
      "output: _put(bowl) # Putting the wood inside the bowl.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Put the battery inside the bowl.",
      "output: _put(bowl) # Putting the battery inside the bowl.",
      "input: You can see a wooden object , white bowl . Put the battery inside the bowl.",
      "output: Sorry, I can't see any ball but I can see wood, bowl.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the ball and place it in the bowl.",
      "output: _pickup(ball)place(bowl) # Picking up the ball and placing it in the bowl.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the wood and drop it in the bowl.",
      "output: _pickup(wood)place(bowl) # Picking up the wood and dropping it in the bowl.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the battery and put it in the bowl.",
      "output: _pickup(battery)place(bowl) # Picking up the battery and putting it in the bowl.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the yellow object and place it in the bowl.",
      "output: _pickup(ball)place(bowl) # Picking up the yellow object and placing it in the bowl.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the silver object and drop it in the bowl.",
      "output: _pickup(battery)place(bowl) # Picking up the silver object and dropping it in the bowl.",
      "input: You can see a yellow ball , silver battery , wooden object , white bowl . Pick up the wood-colored object and put it in the bowl.",
      "output: _pickup(wood)place(bowl) # Picking up the wood-colored object and putting it in the bowl.",
      "input: Retrieve the battery and place it inside the bowl.",
      "output: _pickup(battery)place(bowl) # Retrieving the battery and placing it inside the bowl.",
      "input: Lift the battery and position it within the bowl.",
      "output: _pickup(battery)place(bowl) # Lifting the battery and positioning it within the bowl.",
      "input: Grasp the battery and insert it into the bowl.",
      "output: _pickup(battery)place(bowl) # Grasping the battery and inserting it into the bowl.",
      "input: Collect the battery and carefully place it in the bowl.",
      "output: _pickup(battery)place(bowl) # Collecting the battery and carefully placing it in the bowl.",
      "input: Take the battery, then deposit it into the bowl.",
      "output: _pickup(battery)place(bowl) # Taking the battery, then depositing it into the bowl.",
      "input: Pick up the battery and neatly place it inside the bowl.",
      "output: _pickup(battery)place(bowl) # Picking up the battery and neatly placing it inside the bowl.",
      "input: Retrieve the battery and slide it into the bowl.",
      "output: _pickup(battery)place(bowl) # Retrieving the battery and sliding it into the bowl.",
      "input: Lift the battery and drop it gently into the bowl.",
      "output: _pickup(battery)place(bowl) # Lifting the battery and dropping it gently into the bowl.",
      "input: Grasp the battery and carefully position it in the bowl.",
      "output: _pickup(battery)place(bowl) # Grasping the battery and carefully positioning it in the bowl.",
      "input: Collect the battery and set it down within the bowl.",
      "output: _pickup(battery)place(bowl) # Collecting the battery and setting it down within the bowl.",
      "input: Lift the ball.",
      "output: _pickup(ball) # Lifting the ball.",
      "input: Grab the wood.",
      "output: _pickup(wood) # Grabbing the wood.",
      "input: Retrieve the battery.",
      "output: _pickup(battery) # Retrieving the battery.",
      "input: Collect the yellow object.",
      "output: _pickup(ball) # Collecting the yellow object.",
      "input: Take the silver item.",
      "output: _pickup(battery) # Taking the silver item.",
      "input: Hold the wood-colored object.",
      "output: _pickup(wood) # Holding the wood-colored object.",
      "input: Shift slightly to the right.",
      "output: _move(right) # Shifting slightly to the right.",
      "input: Navigate left.",
      "output: _move(left) # Navigating left.",
      "input: Move to the right.",
      "output: _move(right) # Moving to the right.",
      "input: Slide to the left.",
      "output: _move(left) # Sliding to the left.",
      "input: Adjust position downwards.",
      "output: _move(down) # Adjusting position downwards.",
      "input: Shift upwards.",
      "output: _move(up) # Shifting upwards.",
      "input: Release the object.",
      "output: _drop() # Releasing the object.",
      "input: Let go of the ball.",
      "output: _drop() # Letting go of the ball.",
      "input: Drop the wood.",
      "output: _drop() # Dropping the wood.",
      "input: Release the battery.",
      "output: _drop() # Releasing the battery.",
      "input: Let go of the yellow item.",
      "output: _drop() # Letting go of the yellow item.",
      "input: Drop the silver object.",
      "output: _drop() # Dropping the silver object.",
      "input: Place the ball inside the container.",
      "output: _put(bowl) # Placing the ball inside the container.",
      "input: Insert the wood into the bowl.",
      "output: _put(bowl) # Inserting the wood into the bowl.",
      "input: Position the battery inside the container.",
      "output: _put(bowl) # Positioning the battery inside the container.",
      "input: Put the yellow object into the bowl.",
      "output: _put(bowl) # Putting the yellow object into the bowl.",
      "input: Set down the wood-colored item inside the container.",
      "output: _put(bowl) # Setting down the wood-colored item inside the container.",
      "input: Insert the silver object into the bowl.",
      "output: _put(bowl) # Inserting the silver object into the bowl.",
      "input: Place the ball on the surface.",
      "output: _place(bowl) # Placing the ball on the surface.",
      "input: Set the wood on the table.",
      "output: _place(bowl) # Setting the wood on the table.",
      "input: Position the battery on the shelf.",
      "output: _place(bowl) # Positioning the battery on the shelf.",
      "input: Place the yellow object on the platform.",
      "output: _place(bowl) # Placing the yellow object on the platform.",
      "input: Set down the wood-colored item.",
      "output: _place(bowl) # Setting down the wood-colored item.",
      "input: Position the silver object on the stand.",
      "output: _place(bowl) # Positioning the silver object on the stand.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Move slightly up",
      "output: _move(up) # Moving slightly up.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Move slightly left",
      "output: _move(left) # Moving left.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Move left",
      "output: _move(left) # Moving left.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Move right",
      "output: _move(right) # Moving right.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Move down",
      "output: _move(down) # Moving down.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Pick up the ball",
      "output: _pickup(ball) # Picking up the ball.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Pick up the wood",
      "output: _pickup(wood) # Picking up the wood.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Pick up the battery",
      "output: _pickup(battery) # Picking up the battery.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Pick up the yellow object",
      "output: _pickup(ball) # Picking up the yellow object.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Pick up the wood-colored object",
      "output: _pickup(wood) # Picking up the wood-colored object.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Pick up the silver object",
      "output: _pickup(battery) # Picking up the silver object.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Drop the object",
      "output: _drop() # Dropping the object.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Drop the ball",
      "output: _drop() # Dropping the ball.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Drop the wood",
      "output: _drop() # Dropping the wood.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Drop the battery",
      "output: _drop() # Dropping the battery.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Put the ball inside the bowl",
      "output: _put(bowl) # Putting the ball inside the bowl.",
      "input: You can see a silver battery, wooden object, white bowl. Put the ball inside the bowl.",
      "output: Sorry, I can't see any ball but I can see battery, wood, bowl.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Put the wood inside the bowl",
      "output: _put(bowl) # Putting the wood inside the bowl.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Put the battery inside the bowl",
      "output: _put(bowl) # Putting the battery inside the bowl.",
      "input: You can see a wooden object, white bowl. Put the battery inside the bowl.",
      "output: Sorry, I can't see any ball but I can see wood, bowl.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Pick up the ball and place it in the bowl",
      "output: _pickup(ball)place(bowl) # Picking up the ball and placing it in the bowl.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Pick up the wood and drop it in the bowl",
      "output: _pickup(wood)place(bowl) # Picking up the wood and dropping it in the bowl.",
      "input: You can see a yellow ball, silver battery, wooden object, white bowl. Pick up the battery and put it in the bowl",
      "output: _pickup(battery)place(bowl) # Picking up the battery and putting it in the bowl.",
      f"input:{msg} ",
      "output: ",
      ]
    response = model.generate_content(prompt_parts)

    return response.text
